import EarthScienceEconomicGeologyTheoremCanonicalLaneLean.AdmissibleClass
import EarthScienceEconomicGeologyTheoremCanonicalLaneLean.BridgeLemmas
import EarthScienceEconomicGeologyTheoremCanonicalLaneLean.GateLemmas
import EarthScienceEconomicGeologyTheoremCanonicalLaneLean.FinalTheorem
import EarthScienceEconomicGeologyTheoremCanonicalLaneLean.GeologicalResourceModel
import EarthScienceEconomicGeologyTheoremCanonicalLaneLean.EconomicEvaluation
import EarthScienceEconomicGeologyTheoremCanonicalLaneLean.ResourceExtraction
import EarthScienceEconomicGeologyTheoremCanonicalLaneLean.MarketAnalysis

namespace HautevilleHouse
namespace EarthScienceEconomicGeologyTheoremCanonicalLaneLean

-- Root module for Earth Science Economic Geology Theorem Canonical Lane Lean

end EarthScienceEconomicGeologyTheoremCanonicalLaneLean
end HautevilleHouse